### ISSUE TITLE
Exclude properties

### ISSUE THREAD

**Issue by BlizzzArt** [cuth/gulp-pxtorem#2]
Has any feature to exclude the propertie? For example "line-height" for vertical align in a element. I need only 'px' because line-height in rem not make vertical align in the element with height in px

**Comment by mekela** [comment]
+ 
any news about this issue?

**Comment by cuth** [comment]
I've update with PR #4 and now you can use `propList` option like this `['*', '!line-height']`.

https://github.com/cuth/postcss-pxtorem
