### ISSUE TITLE
Must use propWhiteList instead of propList

### ISSUE THREAD

**Issue by stevepiron** [cuth/gulp-pxtorem#3]
Hello,

I've noticed that even though the documentation for `postcss-pxtorem` uses `propList` as an option, it seems like `gulp-pxtorem` still requires the old syntax to be used which is `propWhiteList`.

It's only after searching for a while that I found out about this older syntax, tried it out and noticed it was working that way.

**Comment by cuth** [comment]
Thanks for finding that

**Comment by cuth** [comment]
Updated the `postcss-pxtorem` dependency with #4
